version: '3.5'
services:
  loan-broker-aggregator:
    build:
      context: ./loan-broker-aggregator
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  loan-broker-normalizer:
    build:
      context: ./loan-broker-normalizer
      dockerfile: Dockerfile
    depends_on:
    - rabbitmq

  loan-broker-translator-xml:
    build:
      context: ./loan-broker-bank-translator-xml
      dockerfile: Dockerfile
    depends_on:
    - rabbitmq

  loan-broker-translator-json:
    build:
      context: ./loan-broker-bank-translator-json
      dockerfile: Dockerfile
    depends_on:
    - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

networks:
  default:
    driver: bridge
