version: '3.5'
services:
  loan-broker-api:
    build:
      context: ./loan-broker-api
      dockerfile: Dockerfile
    command: mvn spring-boot:run
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq

  loan-broker-aggregator:
    build:
      context: ./loan-broker-aggregator
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  loan-broker-normalizer:
    build:
      context: ./loan-broker-normalizer
      dockerfile: Dockerfile
    depends_on:
    - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 15672:15672
      - 5672:5672

networks:
  default:
    driver: bridge
