
package creditbureau;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditScoreService", targetNamespace = "http://service.web.credit.bank.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditScoreService {


    /**
     * 
     * @param ssn
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creditScore", targetNamespace = "http://service.web.credit.bank.org/", className = "creditbureau.CreditScore")
    @ResponseWrapper(localName = "creditScoreResponse", targetNamespace = "http://service.web.credit.bank.org/", className = "creditbureau.CreditScoreResponse")
    @Action(input = "http://service.web.credit.bank.org/CreditScoreService/creditScoreRequest", output = "http://service.web.credit.bank.org/CreditScoreService/creditScoreResponse")
    public int creditScore(
        @WebParam(name = "ssn", targetNamespace = "")
        String ssn);

}
