
package rulebase;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://rulebase/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param creditScore
     * @param loanAmount
     * @return
     *     returns java.util.List<rulebase.Bank>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeLoan", targetNamespace = "http://rulebase/", className = "rulebase.MakeLoan")
    @ResponseWrapper(localName = "makeLoanResponse", targetNamespace = "http://rulebase/", className = "rulebase.MakeLoanResponse")
    @Action(input = "http://rulebase/BankService/makeLoanRequest", output = "http://rulebase/BankService/makeLoanResponse")
    public List<Bank> makeLoan(
        @WebParam(name = "creditScore", targetNamespace = "")
        int creditScore,
        @WebParam(name = "loanAmount", targetNamespace = "")
        double loanAmount);

}
