
package rulebase;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BanksPortService", targetNamespace = "http://spring.io/guides/gs-producing-web-service", wsdlLocation = "http://localhost:8080/ws/banks.wsdl")
public class BanksPortService
    extends Service
{

    private final static URL BANKSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKSPORTSERVICE_EXCEPTION;
    private final static QName BANKSPORTSERVICE_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "BanksPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/banks.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKSPORTSERVICE_WSDL_LOCATION = url;
        BANKSPORTSERVICE_EXCEPTION = e;
    }

    public BanksPortService() {
        super(__getWsdlLocation(), BANKSPORTSERVICE_QNAME);
    }

    public BanksPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKSPORTSERVICE_QNAME, features);
    }

    public BanksPortService(URL wsdlLocation) {
        super(wsdlLocation, BANKSPORTSERVICE_QNAME);
    }

    public BanksPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKSPORTSERVICE_QNAME, features);
    }

    public BanksPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanksPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanksPort
     */
    @WebEndpoint(name = "BanksPortSoap11")
    public BanksPort getBanksPortSoap11() {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "BanksPortSoap11"), BanksPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanksPort
     */
    @WebEndpoint(name = "BanksPortSoap11")
    public BanksPort getBanksPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "BanksPortSoap11"), BanksPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKSPORTSERVICE_EXCEPTION!= null) {
            throw BANKSPORTSERVICE_EXCEPTION;
        }
        return BANKSPORTSERVICE_WSDL_LOCATION;
    }

}
