
package rulebase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanksPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanksPort {


    /**
     * 
     * @param getBanksRequest
     * @return
     *     returns rulebase.GetBanksResponse
     */
    @WebMethod
    @WebResult(name = "getBanksResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBanksResponse")
    public GetBanksResponse getBanks(
        @WebParam(name = "getBanksRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBanksRequest")
        GetBanksRequest getBanksRequest);

}
